### PR TITLE
Add TokenTimerColor & Logos

### PR DESCRIPTION
**Pull request by Plus1XP**

### CODE REVIEW

**Comment by bingzheung** [comment]
Hi @Plus1XP 

Thank you for the PR!

I think the countdown arc colors may attract too much attention, and I'd prefer to keep the the app's main colors stay black and white.

Therefore, I prefer not to merge this PR. And I suggest you keep your fork and develop it to be what you want.

Thank you very much.

**Comment by Plus1XP** [comment]
No Problem, I plan to add face ID and maybe groups for personal/work etc. if you would like a PR for those features just send me a request once they are done.

Thanks for sharing!

**Comment by Akczht** [comment]
> No Problem, I plan to add face ID and maybe groups for personal/work etc. if you would like a PR for those features just send me a request once they are done.
> 
> 
> 
> Thanks for sharing!

Are you planning to publish the app on appstore ?

**Comment by Plus1XP** [comment]
@Akczht I wasnt going to but if you are interested i can.

**Comment by Akczht** [comment]
@Plus1XP I'll love to see it , Thanks! , a few suggestions I'd also love to see are , please add a feature for search , icloud backup and custom icons , and Please! Make it telemetry free & no in app purchases if you can . It's too much to ask for .

**Comment by Akczht** [comment]
> @Akczht I wasnt going to but if you are interested i can.

It's okay if you don't want to .

**Comment by Plus1XP** [comment]
@Akczht ill give it a go, may take a while as I'm busy with work atm. I'll tag you in when I've got some thing decent

**Comment by Akczht** [comment]
@Plus1XP Gotcha

**Comment by Plus1XP** [comment]
@Akczht i have updated the app and have a build up on TestFlight 

https://testflight.apple.com/join/utjLiEug

Adding custom logos will be a while as I have to work on some other stuff but if you need some specific ones added let me know..

Hope you enjoy

**Comment by Akczht** [comment]
@Plus1XP Thanks for remembering this , Please make the copied message as a fade in and fade out animation within the timespace of 500ms and screen time for it fading in is 250ms and fading out for 250ms , I think the copied text sliding from left is  a little off-ish , please change its colour to greyish like , and also when one adds a microsoft 2FA secret key then there are spaces in the key and the app thinks the key is invalid so if you can add something that detects the spaces and removes those space , would removing those spaces change the otps ? ,  and also there is something that makes the app to stop scrolling , while scrolling rapidly and then you have to lift up the finger and then scroll again , while scrolling gently is all fine . And the app otherwise is amazing with icloud support and profiles ,

Thanks! A lot
and have a good day

**Pull request closed without merging**
